function loadviddb() {
	 url=';https://www.youtube.com/watch?v=5pLCmLgjiJ8';
	preview='http://www.youtube.com/embed/5pLCmLgjiJ8';
	title=';Dogs | Official Trailer [HD] | Netflix';
	source='Netflix';
	sourceurl='https://www.youtube.com/channel/UCWOA1ZGywLbqmigxE4Qlvuw';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 
	url=';https://www.youtube.com/watch?v=IACqfc8BtK4';
	preview='http://www.youtube.com/embed/IACqfc8BtK4';
	title=';Dogs: Season 2 | Official Trailer | Netflix';
	source='Netflix';
	sourceurl='https://www.youtube.com/channel/UCWOA1ZGywLbqmigxE4Qlvuw';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 
	url=';https://www.youtube.com/watch?v=q1adV0O7JmA';
	preview='http://www.youtube.com/embed/q1adV0O7JmA';
	title=';Dogs &amp; us - The secrets of an unbreakable friendship | DW Documentary';
	source='DW Documentary';
	sourceurl='https://www.youtube.com/channel/UCW39zufHfsuGgpLviKh297Q';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 
	url=';https://www.youtube.com/watch?v=MPV2METPeJU';
	preview='http://www.youtube.com/embed/MPV2METPeJU';
	title=';The Best Dogs of BBC Earth | Top 5 | BBC Earth';
	source='BBC Earth';
	sourceurl='https://www.youtube.com/channel/UCwmZiChSryoWQCZMIQezgTg';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 
	url=';https://www.youtube.com/watch?v=V4tAtp-TyzQ';
	preview='http://www.youtube.com/embed/V4tAtp-TyzQ';
	title=';DOG | Official Trailer | MGM Studios';
	source='MGM';
	sourceurl='https://www.youtube.com/channel/UCf5CjDJvsFvtVIhkfmKAwAA';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 
	url=';https://www.youtube.com/watch?v=8RkwC7Ld3_0';
	preview='http://www.youtube.com/embed/8RkwC7Ld3_0';
	title=';Top 5 Dog Breeds I would NOT Own As A Veterinarian';
	source='Dr. Rachel, Exotic Pet Vet';
	sourceurl='https://www.youtube.com/channel/UCW7N8-fkWwbCKXUG9zp1MAA';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 
	url=';https://www.youtube.com/watch?v=JJVFSWHZYjY';
	preview='http://www.youtube.com/embed/JJVFSWHZYjY';
	title=';100 FACTS About DOGS That Will Surprise You 🐶🐾 Discover them!';
	source='AnimalWised';
	sourceurl='https://www.youtube.com/channel/UCehBsZIPmlXUedqF9bKRSqw';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 
	url=';https://www.youtube.com/watch?v=B7yOO4oKMVc';
	preview='http://www.youtube.com/embed/B7yOO4oKMVc';
	title=';Shelter dog realizes he’s been adopted';
	source='We Love Animals';
	sourceurl='https://www.youtube.com/channel/UCz2RMMEv5CNrOKJhs7BvLpw';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 
	url=';https://www.youtube.com/watch?v=KgqOFVwYxss';
	preview='http://www.youtube.com/embed/KgqOFVwYxss';
	title=';The Most Recently Discovered Dogs In The World';
	source='4 Ever Green';
	sourceurl='https://www.youtube.com/channel/UCRpNVpZoW56rOsV-6wFK3lg';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 
	url=';https://www.youtube.com/watch?v=hjqFrNmUSyU';
	preview='http://www.youtube.com/embed/hjqFrNmUSyU';
	title=';Dog needs emotional support ball during his grooming';
	source='Girl With The Dogs';
	sourceurl='https://www.youtube.com/channel/UCUFnGWHIQvybwmR7XDh7-9A';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 
	url=';https://www.youtube.com/watch?v=ALkPeEE6fqQ';
	preview='http://www.youtube.com/embed/ALkPeEE6fqQ';
	title=';Baby Dogs 🔴 Cute and Funny Dog Videos Compilation #31 | 30 Minutes of Funny Puppy Videos 2022';
	source='Grumpy Dogs';
	sourceurl='https://www.youtube.com/channel/UCbHvtJxBXUzpB_iXfJLIvjA';
	tag='dogs';
	vidtmp=[url, preview, title, source, sourceurl, tag]; 
	vid.push(vidtmp); 

}

function clearviddb() {
	vid.length = 0;
}